#!/bin/bash
#
#
# author : fouad ghaoui
# Tested on Kali Linux / Parrot Os / Ubuntu/ Arco Linux / Archman 
# Simple script for Install dwtinfo
#Colors
cyan='\e[0;36m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
#Options
path=`pwd` # Path
VeR="V3.6" # Version
#Check root exist
[[ `id -u` -eq 0 ]] > /dev/null 2>&1 || { echo  $red "You must be root to run the script"; exit 1; }
echo -e $cyan ""
echo "    ____                  __      _ __     ";
echo "   / __ \___ _ __  / /___  (_) /_    ";
echo "  / / / / _ \ | / / __ \/ / __ \/ / __/    ";
echo " / /_/ /  __/ |/ / /_/ / /_/ / / /_      ";
echo "/_____/\___/|___/ /\____/_/\__/$VeR     ";
echo "               /_/                         ";
echo -e $white "------------------------------"
echo -e $red "[ ✔ ] Installer The Tool [ ✔ ] "; 
echo -e $white "------------------------------"
echo -e $green "[ ! ] Moving dwtinfo folder "
mkdir /usr/share/dwtinfo
cp -r Dev /usr/share/dwtinfo
cp install /usr/share/dwtinfo  
cp update.py /usr/share/dwtinfo
cp -r modules /usr/share/dwtinfo
cp dwtinfo.py /usr/share/dwtinfo
echo -e $blue "[ ✔ ]Done"
echo -e $red "[*] Creating Icons Dirctory"
cp -r $path/Dev/dwtinfo.desktop /usr/share/applications/dwtinfo.desktop
cp -r $path/Dev/dwtinfo.png /usr/share/icons/dwtinfo.png
echo -e $yellow "[*] Creating shortcut command $red dwtinfo"
echo "#!/bin/sh" >> /usr/bin/dwtinfo  
echo "cd /usr/share/dwtinfo" >> /usr/bin/dwtinfo  
echo "exec python2 dwtinfo.py \"\$@\"" >> /usr/bin/dwtinfo  
chmod +x /usr/bin/dwtinfo  
echo -e $white "------------------------------------------------------------------------"
echo -e $red "[ ✔ ] dwtinfo Is Installed In Application (information gathering) [ ✔ ]"
echo -e $white "------------------------------------------------------------------------"
echo -e $green"╔────────────────────────────╗ "
echo -e $blue "|Run in Terminal<(dwtinfo)> |  "
echo -e $green"╚────────────────────────────╝ "
exit